#!/bin/bash
# Protect master from accidental commits.
# if getting "syntax error: unexpected end of file" click the bottom right CRLF change to LF
# set LF as default end of line: Setting -> Text Editor -> File -> EOL -> \n (is LF)
echo -e "===\n>> Pre-commit Hook:: Checking branch name..."
branchName=$(git branch | grep '*' | sed 's/* //')
if [ $branchName == 'main' ]
then
  echo -e "\n🚫 Commit directly to master branch is not allowed! \n" && exit 1
fi
if [ $branchName == 'develop' ]
then
  echo -e "\n🚫 Cannot push to remote develop branch, please create your own branch and use PR." && exit 1
fi
echo -e ">> Finish checking branch name. \n==="
exit 0