#!/bin/bash
# Prevents force-pushing to main
# if getting "syntax error: unexpected end of file" click the bottom right CRLF change to LF
# set LF as default end of line: Setting -> Text Editor -> File -> EOL -> \n (is LF)
echo -e "===\n>> Pre-push Hook: Checking branch name..."
BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(main|develop)"
if [[ $1 != *"$BRANCH"* ]]
then
  echo -e "\n🚫 You must use (git push origin $BRANCH).\n" && exit 1
fi
if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
then
  echo -e "\n🚫 Cannot push to remote $BRANCH branch, please create your own branch and use PR." && exit 1
fi
echo -e ">> Finish checking branch name. \n==="
exit 0
